# Generated by Django 3.2 on 2023-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
