# Generated by Django 3.2 on 2023-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_attendees'),
    ]

    operations = [
    ]
