# Generated by Django 3.2 on 2023-07-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20230716_1127'),
        ('event', '0008_auto_20230716_1518'),
    ]

    operations = [
    ]
